export const DEFAULT_SERVICES = [
  {
    slug: 'gbo-4cyl',
    name: 'ГБО на 4 цилиндра',
    category: 'install',
    basePrice: 38000,
    durationMin: 300,
    description: 'Распределённый впрыск (MPI). Базовый комплект Lovato/BRC/Digitronic.',
  },
  {
    slug: 'gbo-6cyl',
    name: 'ГБО на 6 цилиндров',
    category: 'install',
    basePrice: 48000,
    durationMin: 360,
    description: 'Для V6/L6 моторов. 6 форсунок, усиленный редуктор.',
  },
  {
    slug: 'gbo-8cyl',
    name: 'ГБО на 8 цилиндров (V8)',
    category: 'install',
    basePrice: 65000,
    durationMin: 480,
    description: 'V8 для крупных внедорожников и пикапов. Два редуктора, 8 форсунок.',
  },
  {
    slug: 'gbo-direct-injection',
    name: 'ГБО на прямой впрыск',
    category: 'install',
    basePrice: 95000,
    durationMin: 480,
    description:
      'GDI / FSI / TSI / D-4S. Оборудование Prins VSI-DI, OMVL DREAM — защита форсунок и сохранение ресурса.',
  },
  {
    slug: 'gbo-combined',
    name: 'ГБО на комбинированный впрыск',
    category: 'install',
    basePrice: 110000,
    durationMin: 540,
    description:
      'Двойной впрыск (прямой + распределённый): Toyota D-4S, Volvo VEA, Audi TFSI. Prins и OMVL.',
  },
  {
    slug: 'gbo-diagnostic',
    name: 'Диагностика ГБО',
    category: 'diagnostic',
    basePrice: 1500,
    durationMin: 60,
    description: 'Проверка редуктора, форсунок, датчиков, калибровка.',
  },
  {
    slug: 'gbo-repair',
    name: 'Ремонт ГБО',
    category: 'repair',
    basePrice: 3000,
    durationMin: 120,
    description: 'Замена редуктора / форсунок / клапанов, ремонт проводки.',
  },
  {
    slug: 'gbo-recheck',
    name: 'Поверка баллона',
    category: 'inspection',
    basePrice: 2500,
    durationMin: 90,
    description: 'Композитный — раз в 2 года, металлический — раз в 5 лет.',
  },
  {
    slug: 'gbo-tune',
    name: 'Настройка ГБО',
    category: 'tune',
    basePrice: 2000,
    durationMin: 90,
    description: 'Прошивка ЭБУ, калибровка карт, устранение провалов.',
  },
] as const;

export const PART_CATEGORIES = [
  { slug: 'reducers', name: 'Редукторы' },
  { slug: 'injectors', name: 'Форсунки' },
  { slug: 'cylinders', name: 'Баллоны' },
  { slug: 'valves', name: 'Клапаны' },
  { slug: 'ecu', name: 'Электронные блоки (ЭБУ)' },
  { slug: 'filters', name: 'Фильтры' },
  { slug: 'hoses', name: 'Шланги и трубки' },
  { slug: 'fittings', name: 'Фитинги и арматура' },
  { slug: 'kits', name: 'Комплекты для установки' },
  { slug: 'other', name: 'Прочее' },
] as const;
