export const DEFAULT_SERVICES = [
  {
    slug: 'gbo-install-2gen',
    name: 'Установка ГБО 2-го поколения',
    category: 'install',
    basePrice: 22000,
    durationMin: 240,
    description: 'Инжекторные карбюраторные авто, базовый комплект.',
  },
  {
    slug: 'gbo-install-4gen',
    name: 'Установка ГБО 4-го поколения',
    category: 'install',
    basePrice: 38000,
    durationMin: 360,
    description: 'Электронные форсунки, ЭБУ, наиболее популярный вариант.',
  },
  {
    slug: 'gbo-install-6gen',
    name: 'Установка ГБО 6-го поколения',
    category: 'install',
    basePrice: 95000,
    durationMin: 480,
    description: 'Прямой впрыск газа, современные двигатели.',
  },
  {
    slug: 'gbo-diagnostic',
    name: 'Диагностика ГБО',
    category: 'diagnostic',
    basePrice: 1500,
    durationMin: 60,
    description: 'Проверка редуктора, форсунок, датчиков, калибровка.',
  },
  {
    slug: 'gbo-repair',
    name: 'Ремонт ГБО',
    category: 'repair',
    basePrice: 3000,
    durationMin: 120,
    description: 'Замена редуктора/форсунок/клапанов, ремонт проводки.',
  },
  {
    slug: 'gbo-recheck',
    name: 'Поверка баллона',
    category: 'inspection',
    basePrice: 2500,
    durationMin: 90,
    description: 'Обязательная поверка баллона: композитный — раз в 2 года, металлический — раз в 5 лет.',
  },
  {
    slug: 'gbo-tune',
    name: 'Настройка и калибровка ГБО',
    category: 'tune',
    basePrice: 2000,
    durationMin: 90,
    description: 'Прошивка ЭБУ, калибровка карт, устранение провалов и детонации.',
  },
] as const;

export const PART_CATEGORIES = [
  { slug: 'reducers', name: 'Редукторы' },
  { slug: 'injectors', name: 'Форсунки' },
  { slug: 'cylinders', name: 'Баллоны' },
  { slug: 'valves', name: 'Клапаны' },
  { slug: 'ecu', name: 'Электронные блоки (ЭБУ)' },
  { slug: 'filters', name: 'Фильтры' },
  { slug: 'hoses', name: 'Шланги и трубки' },
  { slug: 'fittings', name: 'Фитинги и арматура' },
  { slug: 'kits', name: 'Комплекты для установки' },
  { slug: 'other', name: 'Прочее' },
] as const;
